# Generated by Django 3.0.4 on 2020-03-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='pub_date',
        ),
    ]
