# Generated by Django 3.0.4 on 2020-03-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0002_auto_20200327_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
